### ISSUE TITLE
Need way to accept Mouse Input

### ISSUE THREAD

**Issue by yamamushi** [twitchintheshell/twitch-master#11]
https://activedoc.opensuse.org/book/opensuse-virtualization-with-kvm/chapter-13-administrating-virtual-machines-with-qemu-monitor

Section 13.5

We need a way to parse the variables for mouse input, and a way to only pass the z in for the scroll wheel :)

**Comment by niemal** [comment]
I am on it, ETA unknown.

**Comment by yamamushi** [comment]
:+1:

**Comment by niemal** [comment]
Done.
