### ISSUE TITLE
Monarchy Mode

### ISSUE THREAD

**Issue by yamamushi** [twitchintheshell/twitch-master#14]
Right now, We should put in place a framework to support Monarchy mode.

We also need to discuss the rules for Monarchy mode.

Monarch = Random Player (Future Sub Only?)
Influence = % that votes are modified by
Influence Pool = A high value, every turn the smaller this value, there is a bigger chance of the monarch being overthrown.
Monarchy gets 5x or 10x influence as other player votes (perhaps count viewers?).
Monarchy is slowly eroded, and their influence drops.

Players

Players can choose to fight against the monarchy instead of competing with votes, to speed up the drop in influence the monarch has. 

!rebel - add a negative influence point against the monarchy influence pool.

Ideas and suggestions welcome about this game mode.

**Comment by yamamushi** [comment]
Do not enable this until we have subscriber feature activated.

**Comment by niemal** [comment]
Done (v0.0.5). We could add special perks when we get subscribers.
