### ISSUE TITLE
Specs change

### ISSUE THREAD

**Issue by miguemely** [twitchintheshell/twitch-master#16]
Because of how windows 7 and higher will react to the CPU, is there any way we can bump up the CPU cores to 2-4?

**Comment by niemal** [comment]
@jrwr ^

**Comment by niemal** [comment]
https://github.com/twitchintheshell/twitch-master/commit/1b497ee4688c899eaca1d1ac157750e8d2d5bb18

**Comment by yamamushi** [comment]
This should now be resolved.
