### ISSUE TITLE
Chaos Mode

### ISSUE THREAD

**Issue by yamamushi** [twitchintheshell/twitch-master#26]
Here's one that should easy for ya.
# Chaos Mode

All input is passed to the vm.

It would be absolute chaos, as is implied by the mode name.

**Comment by yamamushi** [comment]
To resolve the issue with system_reset, the commands that require votes now should still require votes in Chaos mode.

Also, every system_request shouldn't be counted. Perhaps when system_request reaches a certain threshold, then a vote fires off, then the threshold is reset?

**Comment by niemal** [comment]
https://github.com/twitchintheshell/twitch-master/blob/master/VERSION.md
