### ISSUE TITLE
Mouse movement vote counts non-commands

### ISSUE THREAD

**Issue by ghost** [twitchintheshell/twitch-master#27]
> TwitchInstallsArchLinux: VOTES: '50' = 20%, 'if you type your password in the chat, it is displayed as *****\* to others' = 20%, '-150' = 40%, 'ok' = 20%

**Comment by yamamushi** [comment]
This occurs when a mouse movement command is voted on.

Anything inputted into chat is taken as input, instead of just integers.

**Comment by niemal** [comment]
https://github.com/twitchintheshell/twitch-master/blob/master/VERSION.md
