### ISSUE TITLE
Ability to filter keywords

### ISSUE THREAD

**Issue by yamamushi** [twitchintheshell/twitch-master#28]
It would be helpful, and would make administration much easier, if we had a way of adding words to a blacklist.

If the parser kept track of the current string, and was able to match any of the entered string to the blacklist words, then it would ctrl-c or backspace through the string, or filtered word. 

So "porn", "hentai", "xxx", would be blocked automatically.

We should also be able to drop this list in - > https://github.com/aredo/porn-site-list/blob/master/sites.json , and block with a "reload-filter" command to twitch-master.  

What the stream would see is , someone would enter "porn", and then all of their work would be erased as it backspaced through the word leaving them with an empty string again.

**Comment by niemal** [comment]
https://github.com/twitchintheshell/twitch-master/blob/master/VERSION.md
