### ISSUE TITLE
op access

### ISSUE THREAD

**Issue by yamamushi** [twitchintheshell/twitch-master#30]
This one feature is going to make administration 1000x easier for all of us.

A way to have an op.json list of usernames of people who have direct access to issue commands to twitch_viewer.js via whisper

ie.

/w TwitchInstallsArchLinux system_reset 

Would issue a direct system_reset to be passed on to qemu.

The whitelist prevents others from being able to do it.

:)

**Comment by Zorlin** [comment]
+1. Excellent suggestion.

**Comment by niemal** [comment]
https://github.com/twitchintheshell/twitch-master/commit/5f4e3671dd8da3a0d4b8d3829b68dcad9fdf5761
